name: linters
on: [push]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry
          key: poetry-linters-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-linters-
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry pre-commit
          python -m poetry install
      - name: Run Linters
        run: |
          python -m pre-commit run --all-files
